version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-ses
    versions:
    - 1.11.1000
    - 1.11.1001
    - 1.11.1002
    - 1.11.1003
    - 1.11.1004
    - 1.11.1005
    - 1.11.944
    - 1.11.945
    - 1.11.946
    - 1.11.947
    - 1.11.948
    - 1.11.949
    - 1.11.950
    - 1.11.951
    - 1.11.952
    - 1.11.953
    - 1.11.954
    - 1.11.955
    - 1.11.956
    - 1.11.957
    - 1.11.958
    - 1.11.959
    - 1.11.960
    - 1.11.963
    - 1.11.964
    - 1.11.965
    - 1.11.966
    - 1.11.967
    - 1.11.968
    - 1.11.969
    - 1.11.970
    - 1.11.971
    - 1.11.972
    - 1.11.973
    - 1.11.975
    - 1.11.976
    - 1.11.977
    - 1.11.979
    - 1.11.980
    - 1.11.981
    - 1.11.982
    - 1.11.983
    - 1.11.986
    - 1.11.987
    - 1.11.988
    - 1.11.990
    - 1.11.992
    - 1.11.993
    - 1.11.995
    - 1.11.996
    - 1.11.997
    - 1.11.998
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.fasterxml.jackson.module:jackson-module-kotlin
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: io.sentry:sentry-logback
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: msal
    versions:
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.8
    - 1.4.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: buefy
    versions:
    - 1.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
