image: Visual Studio 2017
environment:
  MYSQL_ROOT_PASSWORD: Password12!
services:
  - mysql
build_script:
  - gradlew.bat build
before_test:
  - mysql -e "create database nhk_test;" --user=root
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
