image: Visual Studio 2017
environment:
  MYSQL_PWD: Password12!
install:
  - choco install mysql
before_build:
  - set PATH=%PATH%;C:\tools\mysql\current\bin
  - mysql -e "create database nhk_test;" --user=root
build_script:
  - gradlew.bat build
before_test:
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
