image: Visual Studio 2017
environment:
  MYSQL_ROOT_PASSWORD: 123456
services:
  - mysql
build_script:
  - gradlew.bat build
before_test:
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
