image: Visual Studio 2017
environment:
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: 123456
  MYSQL_ENV_MYSQL_DATABASE: nhk_test
services:
  - mysql
build_script:
  - gradlew.bat build
before_test:
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
