image: Visual Studio 2017
services:
  - mysql
build_script:
  - gradlew.bat build
before_test:
  - mysqladmin -uroot -pPassword12! password 123456
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
