image: Visual Studio 2017
environment:
  MYSQL_PWD: 123456
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: 123456
services:
  - mysql
build_script:
  - gradlew.bat build
before_test:
  - mysqladmin -uroot -pPassword12! password 123456
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
