version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    environment: 
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks: 
      - nhk
  mysql:
    image: "mysql:8"
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=nhk
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
      - nhk-db:/var/lib/mysql
    networks: 
      - nhk
volumes: 
  nhk-db:
networks: 
  nhk:
