version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    environment: 
      - MYSQL_HOST=mysql
      - MYSQL_USER=nhk
      - MYSQL_PWD=nhk
  mysql:
    image: "mysql:8"
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: nhk
      MYSQL_USER: nhk
      MYSQL_PASSWORD: nhk
    volumes: 
      - nhk-db:/var/lib/mysql
volumes: 
  nhk-db:

